### ISSUE TITLE
Outdated usage examples

### ISSUE THREAD

**Issue by roophieini** [wendigo/chrome-reactive-kotlin#5]
I like to kindly inform that your usage examples are outdated ;) 
I couldn't find `protocol.headless("about:blank", 1280, 1024).blockingGet()`
And I used `protocol.session` instead :) 

But still thanks for awesome library  :+1:

**Comment by wendigo** [comment]
Yes, examples could be outdated due to refactoring (API is not yet stable)

**Comment by wendigo** [comment]
Fixed.
