### ISSUE TITLE
Expose DevToolsProtocol and Browser.fetchInfo API

### ISSUE THREAD

**Issue by zawodskoj** [wendigo/chrome-reactive-kotlin#52]
Browser class does not have any events like targetCreated/targetDestroyed
I need to use CDP directly for these events and the only way to do this is
1. copy "fun fetchInfo" from Browser and create connection with acquired websocket url
2. create DevToolsProtocol via Reflection API

Making this API public is easy and require almost no changes (I can even make PR by myself)
Can you do that?

**Comment by wendigo** [comment]
@zawodskoj fixed :) I'll try to release new version soon

**Comment by wendigo** [comment]
This is now exposed as `Browser` now extends `ProtocolDomains` exactly as `Target` is :)
