### ISSUE TITLE
I want to read the document of this project but happened 404 Not found error.

### ISSUE THREAD

**Issue by leesanghyeok** [wendigo/chrome-reactive-kotlin#54]
like this title, document url happened 404 not fond error.
https://wendigo.github.io/chrome-reactive-kotlin/.

thanks

**Comment by wendigo** [comment]
@leesanghyeok sorry for waiting - this is/was due to how Github Pages works. I've fixed that and documentation is available under https://wendigo.github.io/chrome-reactive-kotlin/. And it's much nicer :)

**Comment by wendigo** [comment]
I've updated the docs and it will be published automatically on update.
