### ISSUE TITLE
Memory leak in WebSocketFramesStream

### ISSUE THREAD

**Issue by t-omas** [wendigo/chrome-reactive-kotlin#57]
Running this simple code leads to unlimited grow of heap size. Target should free up memory after closing or at least it should use some bounded amount of memory.
```
    val browser = Browser.builder().withAddress("localhost:9222").withEventsBufferSize(1).build()
    while(true) {
        browser.target().close()
        Thread.sleep(1000)
    }
    ...
 ```
One possible solution is to switch from unbounded buffer in `WebSocketFramesStream` to bounded buffer. Now you use  `EventsBufferSize`  just as hint for size of the buffer. It would be better to use this [function](https://github.com/ReactiveX/RxJava/blob/c38ea99eee667dcf6cee427a880507e256807813/src/main/java/io/reactivex/rxjava3/subjects/ReplaySubject.java#L212) instead of [this one](https://github.com/ReactiveX/RxJava/blob/c38ea99eee667dcf6cee427a880507e256807813/src/main/java/io/reactivex/rxjava3/subjects/ReplaySubject.java#L184)

**Comment by wendigo** [comment]
Fixed and released in 0.7.1
