### ISSUE TITLE
RequestError deserialization issue

### ISSUE THREAD

**Issue by t-omas** [wendigo/chrome-reactive-kotlin#59]
Chromium can send frame with following structure `{"id":7,"error":{"code":-32000,"message":"Inspected target navigated or closed"},"sessionId":"XXXXXX"}`. In such a case client tries to deserialize this message to object `RequestError`. This deserialization ends up with following exception `Caught WebSocket exception: kotlinx.serialization.MissingFieldException: Field 'data' is required for type with serial name 'pl.wendigo.chrome.protocol.websocket.RequestError', but it was missing`. To fix this issue it should be enough to add default value `null` to this [field](https://github.com/wendigo/chrome-reactive-kotlin/blob/master/src/main/kotlin/pl/wendigo/chrome/protocol/websocket/RequestError.kt#L23). When value is marked as nullable it doesn't mean that it is not required during deserialization. It must have default value to be optional.

Could you fix it and release new version?
Thanks

**Comment by wendigo** [comment]
Fixed and released in 0.7.2
