### ISSUE TITLE
ChromeDebuggerConnection is internal class

### ISSUE THREAD

**Issue by david-sabata** [wendigo/chrome-reactive-kotlin#6]
Hi Mateusz, 
in attempt to get a better control over targets, especially in spawning multiple tabs in multiple browser contexts, I'm hitting a blocker in `ChromeDebuggerConnection`, which is an internal class.
That prevents me from rewriting `HeadlessChromeProtocol.create` on my own :disappointed: 

Is there a reason for that?
It would be great if the library allowed both high-level and low(er)-level approaches

**Comment by wendigo** [comment]
What's your use case @david-sabata ?

**Comment by wendigo** [comment]
Anyway, I've changed some APIs and ChromeDebuggerConnection is no longer internal class
